"""initial_migration

Revision ID: 9f5bf52fe18f
Revises: 
Create Date: 2025-11-13 21:26:38.135757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f5bf52fe18f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_comments_created_at', table_name='task_comments')
    op.drop_index('idx_task_comments_task_id', table_name='task_comments')
    op.drop_index('idx_task_comments_user_id', table_name='task_comments')
    op.drop_table('task_comments')
    op.alter_column('areas', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('areas', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=7),
               server_default=None,
               nullable=False)
    op.alter_column('areas', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               server_default=None,
               nullable=False)
    op.alter_column('areas', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('areas', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('areas', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('idx_areas_is_active', table_name='areas')
    op.drop_index('uk_areas_name', table_name='areas')
    op.create_index(op.f('ix_areas_is_active'), 'areas', ['is_active'], unique=False)
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=True)
    op.drop_table_comment(
        'areas',
        existing_comment='Ã\x81reas o departamentos',
        schema=None
    )
    op.alter_column('notifications', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='Usuario destinatario',
               existing_nullable=False)
    op.alter_column('notifications', 'task_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='Tarea relacionada (si aplica)',
               existing_nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Contenido del mensaje',
               existing_nullable=False)
    op.alter_column('notifications', 'sent_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Fecha de envío',
               existing_nullable=False)
    op.alter_column('notifications', 'read_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de lectura (si aplica)',
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_notifications_read_at', table_name='notifications')
    op.drop_index('idx_notifications_sent_at', table_name='notifications')
    op.drop_index('idx_notifications_task_id', table_name='notifications')
    op.drop_index('idx_notifications_type', table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notifications_task_id'), 'notifications', ['task_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint('fk_notifications_task', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_user', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'notifications',
        existing_comment='Historial de notificaciones',
        schema=None
    )
    op.alter_column('projects', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('projects', 'emoji_icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               server_default=None,
               comment=None,
               existing_comment='Emoji o icono del proyecto',
               existing_nullable=True)
    op.alter_column('projects', 'owner_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='Usuario creador del proyecto',
               existing_nullable=False)
    op.alter_column('projects', 'area_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='Ã\x81rea a la que pertenece el proyecto',
               existing_nullable=True)
    op.alter_column('projects', 'is_archived',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('projects', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_projects_area_id', table_name='projects')
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.drop_index('idx_projects_is_archived', table_name='projects')
    op.drop_index('idx_projects_owner_id', table_name='projects')
    op.create_index(op.f('ix_projects_area_id'), 'projects', ['area_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_archived'), 'projects', ['is_archived'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.drop_constraint('fk_projects_owner', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_area', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'projects', 'areas', ['area_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'projects',
        existing_comment='Proyectos del sistema',
        schema=None
    )
    op.alter_column('tasks', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('sin_empezar', 'en_curso', 'completado', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.ENUM('baja', 'media', 'alta', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'responsible_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='Usuario responsable de la tarea',
               existing_nullable=True)
    op.alter_column('tasks', 'deadline',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Fecha límite para completar la tarea',
               existing_nullable=True)
    op.alter_column('tasks', 'reminder_hours_before',
               existing_type=mysql.INTEGER(unsigned=True),
               server_default=None,
               comment=None,
               existing_comment='Horas antes del deadline para enviar recordatorio',
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Fecha y hora de completado',
               existing_nullable=True)
    op.alter_column('tasks', 'created_by',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='Usuario que creó la tarea',
               existing_nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_index('idx_tasks_created_by', table_name='tasks')
    op.drop_index('idx_tasks_deadline', table_name='tasks')
    op.drop_index('idx_tasks_priority', table_name='tasks')
    op.drop_index('idx_tasks_project_id', table_name='tasks')
    op.drop_index('idx_tasks_project_status', table_name='tasks')
    op.drop_index('idx_tasks_responsible_id', table_name='tasks')
    op.drop_index('idx_tasks_responsible_status', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_status_deadline', table_name='tasks')
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_responsible_id'), 'tasks', ['responsible_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.drop_constraint('fk_tasks_responsible', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_tasks_created_by', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_tasks_project', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['responsible_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'tasks',
        existing_comment='Tareas del sistema',
        schema=None
    )
    op.alter_column('telegram_link_codes', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('telegram_link_codes', 'user_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('telegram_link_codes', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='Código de 6-8 caracteres',
               existing_nullable=False)
    op.alter_column('telegram_link_codes', 'expires_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='Tiempo de expiración (15 minutos)',
               existing_nullable=False)
    op.alter_column('telegram_link_codes', 'used_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='Cuando fue usado',
               existing_nullable=True)
    op.alter_column('telegram_link_codes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_telegram_link_codes_expires_at', table_name='telegram_link_codes')
    op.drop_index('idx_telegram_link_codes_user_id', table_name='telegram_link_codes')
    op.drop_index('uk_telegram_link_codes_code', table_name='telegram_link_codes')
    op.create_index(op.f('ix_telegram_link_codes_code'), 'telegram_link_codes', ['code'], unique=True)
    op.create_index(op.f('ix_telegram_link_codes_expires_at'), 'telegram_link_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_telegram_link_codes_id'), 'telegram_link_codes', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_link_codes_user_id'), 'telegram_link_codes', ['user_id'], unique=False)
    op.drop_constraint('fk_telegram_link_codes_user', 'telegram_link_codes', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_link_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'telegram_link_codes',
        existing_comment='Códigos de vinculación Telegram',
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'telegram_chat_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='Chat ID de Telegram para notificaciones',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('administrador', 'supervisor', 'analista', collation='utf8mb4_unicode_ci'),
               server_default=None,
               comment=None,
               existing_comment='Rol del usuario en el sistema',
               existing_nullable=False)
    op.alter_column('users', 'area_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment=None,
               existing_comment='Ã\x81rea a la que pertenece el usuario',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_users_area_id', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('uk_users_email', table_name='users')
    op.create_index(op.f('ix_users_area_id'), 'users', ['area_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_constraint('fk_users_area', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'areas', ['area_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'users',
        existing_comment='Usuarios del sistema',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Usuarios del sistema',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_area', 'users', 'areas', ['area_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_area_id'), table_name='users')
    op.create_index('uk_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_area_id', 'users', ['area_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'area_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Ã\x81rea a la que pertenece el usuario',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('administrador', 'supervisor', 'analista', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'analista'"),
               comment='Rol del usuario en el sistema',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('users', 'telegram_chat_id',
               existing_type=mysql.BIGINT(),
               comment='Chat ID de Telegram para notificaciones',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
    op.create_table_comment(
        'telegram_link_codes',
        'Códigos de vinculación Telegram',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'telegram_link_codes', type_='foreignkey')
    op.create_foreign_key('fk_telegram_link_codes_user', 'telegram_link_codes', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_telegram_link_codes_user_id'), table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_id'), table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_expires_at'), table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_code'), table_name='telegram_link_codes')
    op.create_index('uk_telegram_link_codes_code', 'telegram_link_codes', ['code'], unique=False)
    op.create_index('idx_telegram_link_codes_user_id', 'telegram_link_codes', ['user_id'], unique=False)
    op.create_index('idx_telegram_link_codes_expires_at', 'telegram_link_codes', ['expires_at'], unique=False)
    op.alter_column('telegram_link_codes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('telegram_link_codes', 'used_at',
               existing_type=mysql.TIMESTAMP(),
               comment='Cuando fue usado',
               existing_nullable=True)
    op.alter_column('telegram_link_codes', 'expires_at',
               existing_type=mysql.TIMESTAMP(),
               comment='Tiempo de expiración (15 minutos)',
               existing_nullable=False)
    op.alter_column('telegram_link_codes', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='Código de 6-8 caracteres',
               existing_nullable=False)
    op.alter_column('telegram_link_codes', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
    op.alter_column('telegram_link_codes', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
    op.create_table_comment(
        'tasks',
        'Tareas del sistema',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('fk_tasks_project', 'tasks', 'projects', ['project_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_tasks_created_by', 'tasks', 'users', ['created_by'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('fk_tasks_responsible', 'tasks', 'users', ['responsible_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_responsible_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.create_index('idx_tasks_status_deadline', 'tasks', ['status', 'deadline'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_responsible_status', 'tasks', ['responsible_id', 'status'], unique=False)
    op.create_index('idx_tasks_responsible_id', 'tasks', ['responsible_id'], unique=False)
    op.create_index('idx_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_tasks_deadline', 'tasks', ['deadline'], unique=False)
    op.create_index('idx_tasks_created_by', 'tasks', ['created_by'], unique=False)
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('tasks', 'created_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Usuario que creó la tarea',
               existing_nullable=False)
    op.alter_column('tasks', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='Fecha y hora de completado',
               existing_nullable=True)
    op.alter_column('tasks', 'reminder_hours_before',
               existing_type=mysql.INTEGER(unsigned=True),
               server_default=sa.text("'24'"),
               comment='Horas antes del deadline para enviar recordatorio',
               existing_nullable=True)
    op.alter_column('tasks', 'deadline',
               existing_type=mysql.DATETIME(),
               comment='Fecha límite para completar la tarea',
               existing_nullable=True)
    op.alter_column('tasks', 'responsible_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Usuario responsable de la tarea',
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.ENUM('baja', 'media', 'alta', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'media'"),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('sin_empezar', 'en_curso', 'completado', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'sin_empezar'"),
               existing_nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
    op.create_table_comment(
        'projects',
        'Proyectos del sistema',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('fk_projects_area', 'projects', 'areas', ['area_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('fk_projects_owner', 'projects', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_archived'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_area_id'), table_name='projects')
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_projects_is_archived', 'projects', ['is_archived'], unique=False)
    op.create_index('idx_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('idx_projects_area_id', 'projects', ['area_id'], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('projects', 'is_archived',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('projects', 'area_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Ã\x81rea a la que pertenece el proyecto',
               existing_nullable=True)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Usuario creador del proyecto',
               existing_nullable=False)
    op.alter_column('projects', 'emoji_icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               server_default=sa.text('0xF09F9381'),
               comment='Emoji o icono del proyecto',
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
    op.create_table_comment(
        'notifications',
        'Historial de notificaciones',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('fk_notifications_user', 'notifications', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_notifications_task', 'notifications', 'tasks', ['task_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_task_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('idx_notifications_task_id', 'notifications', ['task_id'], unique=False)
    op.create_index('idx_notifications_sent_at', 'notifications', ['sent_at'], unique=False)
    op.create_index('idx_notifications_read_at', 'notifications', ['read_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('notifications', 'read_at',
               existing_type=mysql.TIMESTAMP(),
               comment='Fecha de lectura (si aplica)',
               existing_nullable=True)
    op.alter_column('notifications', 'sent_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment='Fecha de envío',
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Contenido del mensaje',
               existing_nullable=False)
    op.alter_column('notifications', 'task_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Tarea relacionada (si aplica)',
               existing_nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Usuario destinatario',
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
    op.create_table_comment(
        'areas',
        'Ã\x81reas o departamentos',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_is_active'), table_name='areas')
    op.create_index('uk_areas_name', 'areas', ['name'], unique=False)
    op.create_index('idx_areas_is_active', 'areas', ['is_active'], unique=False)
    op.alter_column('areas', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('areas', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('areas', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('areas', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               server_default=sa.text("'ðŸ“\x81'"),
               nullable=True)
    op.alter_column('areas', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=7),
               server_default=sa.text("'#3B82F6'"),
               nullable=True)
    op.alter_column('areas', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)
    op.create_table('task_comments',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('task_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_task_comments_task', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_task_comments_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Comentarios en tareas',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Comentarios en tareas',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_task_comments_user_id', 'task_comments', ['user_id'], unique=False)
    op.create_index('idx_task_comments_task_id', 'task_comments', ['task_id'], unique=False)
    op.create_index('idx_task_comments_created_at', 'task_comments', ['created_at'], unique=False)
    # ### end Alembic commands ###
